[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"

winit = "0.30"
pixels = "0.15"
spin_sleep = "1.3"

libgame = { path = "../libgame" }
libml = { path = "../libml" }
