[package]
name = "ml"
version = "0.1.0"
edition = "2024"

[dependencies]
slotmap = { version = "1.0", features = ["serde"] }
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.3"
itertools = "0.14"
chrono = "0.4"

libgame = { path = "../libgame" }
